// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS10blqKlcJXrrNc8cnRjvPbSqA4lEjzE',
    appId: '1:1085696399153:web:f765bd92982ced586d8210',
    messagingSenderId: '1085696399153',
    projectId: 'elkababgee',
    authDomain: 'elkababgee.firebaseapp.com',
    storageBucket: 'elkababgee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbapel1Eyz3Oc3AWB874Fkwu7LiCRgK9U',
    appId: '1:1085696399153:android:8fe4caaa77b603236d8210',
    messagingSenderId: '1085696399153',
    projectId: 'elkababgee',
    storageBucket: 'elkababgee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9kDdnbQdkHwLfcIm2aFh0YgGTzNxDCWk',
    appId: '1:1085696399153:ios:6b7ab043c8ca86b66d8210',
    messagingSenderId: '1085696399153',
    projectId: 'elkababgee',
    storageBucket: 'elkababgee.appspot.com',
    iosBundleId: 'com.example.alkababgee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9kDdnbQdkHwLfcIm2aFh0YgGTzNxDCWk',
    appId: '1:1085696399153:ios:c038d69f9d9fbfc66d8210',
    messagingSenderId: '1085696399153',
    projectId: 'elkababgee',
    storageBucket: 'elkababgee.appspot.com',
    iosBundleId: 'com.example.alkababgee.RunnerTests',
  );
}
